# SwiftLint Configuration File
# https://github.com/realm/SwiftLint

# Disable all rules by default
disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - function_parameter_count

# Enable specific rules
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Custom rules
custom_rules:
  # Custom rule for documentation comments
  documentation_comment:
    name: "Documentation Comment"
    regex: '^\\s*///.*$'
    message: "Use /// for documentation comments"
    severity: warning

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20

function_parameter_count:
  warning: 5
  error: 8

# Exclude patterns
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - Tests/PerformanceTests
  - Examples/AdvancedExamples

# Included patterns
included:
  - Sources
  - Tests/UnitTests
  - Tests/UITests
  - Examples/BasicExamples

# Analyzer rules
analyzer_rules:
  - unused_declaration
  - unused_import
  - unused_private_declaration
